name: 'Release Haskell Package'
description: 'Bumps cabal version and publishes to Hackage'
inputs:
  version: 
    description: 'Who to greet'
    required: true
    default: "${{ github.ref_name }}"
  work-dir:
    description: 'Who to greet'
    required: true
    default: "."
  branch:
    description: "Where to push the commit with the Cabal version bump"
    required: true
    default: "master"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Clean version
      uses: mad9000/actions-find-and-replace-string@1
      id: version
      with:
        source: "${{ inputs.version }}"
        find: 'v'
        replace: ''
    - uses: nikita-volkov/edit-cabal-version.github-action@v1.1.0
      with:
        mode: set
        set-value: "${{ steps.version.outputs.value }}"
        work-dir: "${{ inputs.work-dir }}"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Bumping .cabal to ${{ steps.version.outputs.value  }}"
        branch: "${{ inputs.branch }}"
    - run: cd ${{ inputs.workdir }} && cabal v2-sdist
    - uses: haskell-actions/hackage-publish@v1
      with:
        # http://hackage.haskell.org/users/account-management
        hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
        packagesPath: dist-newstyle/sdist
        #docsPath: ${{ runner.temp }}/docs
        publish: true